[2025-04-28T09-13-35-333Z] ERROR:
Name: Error
Message: UNHANDLED_REJECTION
Stack:
Error: UNHANDLED_REJECTION
    at Object.error (/home/container/events/logger.js:152:27)
    at process.<anonymous> (/home/container/index.js:210:10)
    at process.emit (node:events:518:28)
    at emitUnhandledRejection (node:internal/process/promises:252:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:388:19)
    at processPromiseRejections (node:internal/process/promises:475:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:106:32)
Metadata: {
  "requestBody": {
    "files": [],
    "json": {
      "type": 4,
      "data": {
        "content": "Error al procesar la interacci√≥n",
        "tts": false,
        "enforce_nonce": false,
        "flags": 64
      }
    }
  },
  "rawError": {
    "message": "Interaction has already been acknowledged.",
    "code": 40060
  },
  "code": 40060,
  "status": 400,
  "method": "POST",
  "url": "https://discord.com/api/v10/interactions/1366341567279005696/aW50ZXJhY3Rpb246MTM2NjM0MTU2NzI3OTAwNTY5NjpBTmJPVjdsRDVqdTRxSE90bEN0UXZYcXVpSTdzQ0ZFSkpPNzRqWXRTWmNzR254WmhKWUk1TmlLUUZrZklnRUtwRzFqWHRvM3RWVHBwb1NZNmRZeUY5NHlhOTQxRFlWTEtTWTNaTVlWUnVvU2QzRDBEblBFVHpRcERBUWFOUTQ2Rw/callback?with_response=false"
}

