[2025-04-28T09-17-22-771Z] ERROR:
Name: Error
Message: UNHANDLED_REJECTION
Stack:
Error: UNHANDLED_REJECTION
    at Object.error (/home/container/events/logger.js:152:27)
    at process.<anonymous> (/home/container/index.js:210:10)
    at process.emit (node:events:518:28)
    at emitUnhandledRejection (node:internal/process/promises:252:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:388:19)
    at processPromiseRejections (node:internal/process/promises:475:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:106:32)
Metadata: {
  "requestBody": {
    "files": [],
    "json": {
      "type": 4,
      "data": {
        "content": "Error al procesar la interacci√≥n",
        "tts": false,
        "enforce_nonce": false,
        "flags": 64
      }
    }
  },
  "rawError": {
    "message": "Interaction has already been acknowledged.",
    "code": 40060
  },
  "code": 40060,
  "status": 400,
  "method": "POST",
  "url": "https://discord.com/api/v10/interactions/1366342521273323530/aW50ZXJhY3Rpb246MTM2NjM0MjUyMTI3MzMyMzUzMDowb2JLMDA4Sk5lWXdVZUxSbVFWRWlPM1F6bVhFQUhnTEhRbzBjMmNSQlpYYmVaM0ZBTWVFQzEwbHJ2VFpuZXhrM0pWQVo1WWQxT09sbkw1RXhBSnQ2RlpZS1EyVm5TR1g1TzlhT1JZY0syc2dVWXNGODdNR0I3QkVRT000a2FaOQ/callback?with_response=false"
}

