[2025-04-28T09-25-21-247Z] ERROR:
Name: Error
Message: UNHANDLED_REJECTION
Stack:
Error: UNHANDLED_REJECTION
    at Object.error (/home/container/events/logger.js:152:27)
    at process.<anonymous> (/home/container/index.js:210:10)
    at process.emit (node:events:518:28)
    at emitUnhandledRejection (node:internal/process/promises:252:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:388:19)
    at processPromiseRejections (node:internal/process/promises:475:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:106:32)
Metadata: {
  "requestBody": {
    "files": [],
    "json": {
      "type": 4,
      "data": {
        "content": "Error al procesar la interacci√≥n",
        "tts": false,
        "enforce_nonce": false,
        "flags": 64
      }
    }
  },
  "rawError": {
    "message": "Interaction has already been acknowledged.",
    "code": 40060
  },
  "code": 40060,
  "status": 400,
  "method": "POST",
  "url": "https://discord.com/api/v10/interactions/1366344527794798655/aW50ZXJhY3Rpb246MTM2NjM0NDUyNzc5NDc5ODY1NTpqMUJ6Q1BESW5MbXQ2a1NJMkpqaUV5d0Z6WFd2WEFia0M2YWxZTWpnRFdWVFhjMnpxVGRKMXhFNmV0ZFhWd3JyM3JBdjZ0d2l5cEpFS1lQb2ZmWG54SkpybTNxSXg0bklONEZCeXpHN0VFV21FZXhMcVlhNkl3V1Y2Mko5WFZkQQ/callback?with_response=false"
}

